@startuml
actor Producer
participant "rabbitMQ queue: trades" as TradeEvents
participant "TradeMessageListener" as Consumer
participant "TradeService" as Service
participant "TradeHazelcastService" as HazelcastService
participant "TradeJpaRepository" as JPA
participant "TradeHazelcastRepository" as HZ

Producer -> TradeEvents: send TradeDocument
TradeEvents -> Consumer: deliver message
Consumer -> Service: processTrade(trade)
Service -> JPA: findById(tradeId)
Service -> HazelcastService: getTradeDocument(tradeId)
HazelcastService -> HZ: findById(tradeId)
alt lowerVersion
  Service -> Consumer: throw InvalidTradeException
else ok
  Service -> JPA: save(entity)
  Service -> HZ: save(document)
  Service -> Consumer: ACK
end
@enduml
