name: Spring Boot CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for accurate versioning

      # 2. Set up JDK 17 (or your required version)
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 21
          cache: gradle

      # 3. Cache Gradle dependencies for faster builds
      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: gradle-${{ runner.os }}-

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Validate Gradle configuration
        run: ./gradlew tasks

      # 4. Build and run unit & regression tests
      - name: Build with Gradle
        run: ./gradlew clean build --info


      - name: Install OWASP Dependency Check CLI
        run: |
            mkdir -p tools
            cd tools
            wget https://github.com/jeremylong/DependencyCheck/releases/download/v8.4.3/dependency-check-8.4.3-release.zip
            unzip dependency-check-8.4.3-release.zip
            chmod +x dependency-check/bin/dependency-check.sh

      - name: Run OWASP Dependency Check
        run: |
              ./tools/dependency-check/bin/dependency-check.sh \
                --scan ./ \
                --format ALL \
                --out ./dependency-check-reports \
                --suppression dependency-check-suppressions.xml \
                --nvdApiKey ${{ secrets.NVD_API_KEY }} \
                --failOnCVSS 7 || true

      - name: Generate dependency vulnerability report
        run: |
              echo "# Dependency Vulnerability Analysis" > dependency-analysis.md
              echo "" >> dependency-analysis.md
              echo "**Scan Date:** $(date)" >> dependency-analysis.md
              echo "" >> dependency-analysis.md
    
