name: Spring Boot CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for accurate versioning

      # 2. Set up JDK 17 (or your required version)
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
          cache: gradle

      - name: Verify Java installation
        run: |
          echo "JAVA_HOME: $JAVA_HOME"
          echo "Java version:"
          java -version
          echo "PATH: $PATH"

      # 3. Cache Gradle dependencies for faster builds
      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: gradle-${{ runner.os }}-

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Validate Gradle configuration
        run: ./gradlew tasks

      # 4. Build and run unit & regression tests
      - name: Build with Gradle
        run: ./gradlew clean build --info

      - name: Extract dependencies for scanning
        run: |
          # Generate dependency tree and list
          ./gradlew dependencies --configuration runtimeClasspath > gradle-dependencies.txt || true
          echo "Dependencies extracted to gradle-dependencies.txt"

      # 🔍 Run Trivy Vulnerability Scan
      - name: Run Trivy FS Scan
        uses: aquasecurity/trivy-action@0.12.0
        with:
          scan-type: fs
          scan-ref: .
          severity: CRITICAL,HIGH,MEDIUM,LOW
          ignore-unfixed: true
          format: table
          exit-code: 1

      - name: Install Trivy CLI
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh


      - name: Run Trivy JAR Scan
        run: |
          echo "Scanning built JAR files in build/libs/"
          trivy fs build/libs/ --severity CRITICAL,HIGH,MEDIUM,LOW --ignore-unfixed --exit-code 1