name: Spring Boot CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for accurate versioning

      # 2. Set up JDK 17 (or your required version)
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
          cache: gradle

      - name: Verify Java installation
        run: |
          echo "JAVA_HOME: $JAVA_HOME"
          echo "Java version:"
          java -version
          echo "PATH: $PATH"

      # 3. Cache Gradle dependencies for faster builds
      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: gradle-${{ runner.os }}-

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Validate Gradle configuration
        run: ./gradlew tasks

      # 4. Build and run unit & regression tests
      - name: Build with Gradle
        run: ./gradlew clean build --info

      - name: Extract dependencies for scanning
        run: |
          # Generate dependency tree and list
          ./gradlew dependencies --configuration runtimeClasspath > gradle-dependencies.txt || true
          echo "Dependencies extracted to gradle-dependencies.txt"

      - name: Run Snyk Vulnerability Scan
        uses: snyk/actions/gradle@master
        env:
          SNYK_TOKEN: eb173745-cdd6-4c0a-9f11-9802c98be93c
        with:
          args: --all-projects --severity-threshold=medium --json-file-output=snyk-results.json

      - name: Upload Snyk scan report
        uses: actions/upload-artifact@v3
        with:
          name: snyk-scan-report
          path: snyk-results.json