name: Spring Boot CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for accurate versioning

      # 2. Set up JDK 17 (or your required version)
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
          cache: gradle

      - name: Verify Java installation
        run: |
          echo "JAVA_HOME: $JAVA_HOME"
          echo "Java version:"
          java -version
          echo "PATH: $PATH"

      # 3. Cache Gradle dependencies for faster builds
      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: gradle-${{ runner.os }}-

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Validate Gradle configuration
        run: ./gradlew tasks

      # 4. Build and run unit & regression tests
      - name: Build with Gradle
        run: ./gradlew clean build --info

      - name: Extract dependencies for scanning
        run: |
          # Generate dependency tree and list
          ./gradlew dependencies --configuration runtimeClasspath > gradle-dependencies.txt || true
          echo "Dependencies extracted to gradle-dependencies.txt"
      

      # Dummy Security Scan Step
      - name: Generate Security Scan Results (Dummy)
        run: |
          echo "Running security scan simulation..."
          mkdir -p security-reports
          
          # Create a dummy security scan results file in JSON format
          cat > security-reports/security-scan-results.json << 'EOF'
          {
            "scan_info": {
              "scan_date": "$(date -u +"%Y-%m-%dT%H:%M:%SZ")",
              "scanner": "DummySecurityScanner",
              "version": "1.0.0",
              "project": "spring-boot-gradle-app",
              "total_vulnerabilities": 1,
              "high_severity": 1,
              "medium_severity": 0,
              "low_severity": 0
            },
            "vulnerabilities": [
              {
                "id": "CVE-2023-20873",
                "title": "Spring Framework Remote Code Execution",
                "description": "A remote code execution vulnerability exists in Spring Framework versions prior to 5.3.21. An attacker could exploit this vulnerability by sending specially crafted requests to applications using Spring Framework.",
                "severity": "HIGH",
                "cvss_score": 9.8,
                "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
                "affected_component": "org.springframework:spring-core",
                "affected_versions": "< 5.3.21",
                "fixed_version": "5.3.21",
                "file_path": "build.gradle",
                "line_number": 15,
                "cwe_id": "CWE-94",
                "references": [
                  "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-20873",
                  "https://spring.io/security/cve-2023-20873"
                ],
                "remediation": "Update Spring Framework to version 5.3.21 or later"
              }
            ]
          }
          EOF
          
          # Also create a human-readable summary
          cat > security-reports/security-scan-summary.txt << 'EOF'
          ====================================
          SECURITY SCAN SUMMARY
          ====================================
          Scan Date: $(date -u +"%Y-%m-%d %H:%M:%S UTC")
          Project: Spring Boot Gradle Application
          Scanner: DummySecurityScanner v1.0.0
          
          VULNERABILITY SUMMARY:
          - Total Vulnerabilities Found: 1
          - High Severity: 1
          - Medium Severity: 0
          - Low Severity: 0
          
          HIGH SEVERITY VULNERABILITIES:
          1. CVE-2023-20873 - Spring Framework Remote Code Execution
             Component: org.springframework:spring-core
             CVSS Score: 9.8 (Critical)
             Fix: Update to version 5.3.21 or later
          
          RECOMMENDATION:
          Update your Spring Framework dependencies immediately to address the critical vulnerability.
          ====================================
          EOF
          
          echo "Security scan completed. Results saved to security-reports/"
          ls -la security-reports/

      - name: Upload Security Scan Results
        uses: actions/upload-artifact@v4
        with:
          name: security-scan-results
          path: security-reports/
          retention-days: 30

      # Optional: Fail the build if high severity vulnerabilities are found
      #- name: Check Security Scan Results
      #  run: |
      #    if [ -f security-reports/security-scan-results.json ]; then
      #      high_vulns=$(cat security-reports/security-scan-results.json | grep -o '"high_severity": [0-9]*' | grep -o '[0-9]*')
      #      echo "High severity vulnerabilities found: $high_vulns"
          
      #      if [ "$high_vulns" -gt 0 ]; then
      #        echo "❌ Build failed due to high severity security vulnerabilities!"
      #        echo "Please review the security scan results and fix the issues before proceeding."
      #        exit 1
      #      else
      #        echo "✅ No high severity vulnerabilities found."
      #      fi
      #    fi

  integration_tests:
     name: Integration Tests (RabbitMQ + H2 + Hazelcast)
     runs-on: ubuntu-latest
     needs: build-and-test
     services:
        rabbitmq:
          image: rabbitmq:3.11-management
          ports:
            - 5672:5672
            - 15672:15672
     steps:
        - uses: actions/checkout@v4
        - name: Set up JDK 17
          uses: actions/setup-java@v4
          with:
            distribution: temurin
            java-version: 21
        - name: Run Integration Tests
          run: ./gradlew integrationTest --no-daemon